#! /bin/sh

# setting up the wallpaper
feh --bg-scale ~/.walls/wall11.jpg
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
 
# the composite manager
picom &

# Setting up the notification daemon
dunst -conf ~/.config/dunst/dunstrc &

# the bar
polybar main &

# enable numlock
numlockx on

xsetroot -cursor_name left_ptr &

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config top_padding 20

bspc config window_gap 5

bspc config focused_border_color "#353b45"
bspc config normal_border_color "#282c34"
bspc config border_width 2
bspc config borderless_monocle true

bspc config split_ratio 0.50
bspc config gapless_monocle false

bspc rule -a firefox desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a Screenkey manage=off

# custom configs
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
bspc config focus_follows_pointer true
