#! /bin/sh
feh --bg-scale ~/.walls/wall11.jpg
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
 
# language switch
# setxkbmap -option grp:win_space_toggle us,ar &

#~/.config/polybar/launch.sh
picom &

# Setting up the notification daemon
dunst -conf ~/.config/dunst/dunstrc &

# running the clipboard
parcellite &

# the flameshot
flameshot &

# the polybar 
killall polybar
polybar main &
# bash ~/.config/polybar/launch.sh --forest

# enable numlock
numlockx on

setxkbmap -option caps:swapescape

# setting up the keyboard speed
xset r rate 250 45 

# swapping the caps lock with the esc key
setxkbmap -option caps:escape

# swapping the alt_left with the super key
setxkbmap -option altwin:swap_lalt_lwin

xsetroot -cursor_name left_ptr &

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config top_padding 20

bspc config window_gap 5

bspc config focused_border_color "#353b45"
bspc config normal_border_color "#282c34"
bspc config border_width 2
bspc config borderless_monocle true

bspc config split_ratio 0.50
bspc config gapless_monocle false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# custom configs
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
bspc config focus_follows_pointer true
